### PR TITLE
Command line interface

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/remote-command-server/1)

### CODE REVIEW

**Review by Eb-Zeero — COMMENTED** [review]
> Reviewed 16 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/remote-command-server/1)* status: 16 of 19 files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[pyproject.toml, line 8 at r1](https://reviewable.io/reviews/saltastroops/remote-command-server/1#-MRZikUUE1Y7DyxroAwc:-MRZikUV47l-eoDawYCF:b-md6rdy) ([raw file](https://github.com/saltastroops/remote-command-server/blob/9bc5b2d5fed4a7342834bf089a06494754d9a01c/pyproject.toml#L8)):*
> ```TOML
> 
> [tool.poetry.dependencies]
> python = "^3.7"
> ```

why not use python 3.8 
and 3.9.x is now availble but not yet stable
___
*[remote_command_server/database.py, line 17 at r1](https://reviewable.io/reviews/saltastroops/remote-command-server/1#-MR_V888Dx2WTo17pg-t:-MR_V888Dx2WTo17pg-u:b-clllam) ([raw file](https://github.com/saltastroops/remote-command-server/blob/9bc5b2d5fed4a7342834bf089a06494754d9a01c/remote_command_server/database.py#L17)):*
> ```Python
> 
> 
> def database_connection(database_url: str) -> DatabaseConnection:
> ```

why connect to so may database 
___
*[remote_command_server/schemas.py, line 37 at r1](https://reviewable.io/reviews/saltastroops/remote-command-server/1#-MRZjpWUC9gi9zuC2S_3:-MRZjpWUC9gi9zuC2S_4:b-3f29p0) ([raw file](https://github.com/saltastroops/remote-command-server/blob/9bc5b2d5fed4a7342834bf089a06494754d9a01c/remote_command_server/schemas.py#L37)):*
> ```Python
> 
>     id: int
>     hashed_token: str
> ```

Out of curiosity  why doyou need to query for this Hashed_token
___
*[tests/test_cli.py, line 125 at r1](https://reviewable.io/reviews/saltastroops/remote-command-server/1#-MR_SHmG2Eyc9-gMt-Wc:-MR_SHmG2Eyc9-gMt-Wd:bpo5f7h) ([raw file](https://github.com/saltastroops/remote-command-server/blob/9bc5b2d5fed4a7342834bf089a06494754d9a01c/tests/test_cli.py#L125)):*
> ```Python
> 
>     # check this has failed
>     print(result.output)
> ```

debug statement
___
*[tests/test_cli.py, line 295 at r1](https://reviewable.io/reviews/saltastroops/remote-command-server/1#-MR_SM1WCTZSOE94fxYy:-MR_SM1WCTZSOE94fxYz:b-7e0ber) ([raw file](https://github.com/saltastroops/remote-command-server/blob/9bc5b2d5fed4a7342834bf089a06494754d9a01c/tests/test_cli.py#L295)):*
> ```Python
>     runner = CliRunner()
>     result = runner.invoke(cli, ["initdb", str(db_file)])
>     print(result.output)
> ```

DEbug statement
___
*[tests/test_remote_command_server.py, line 30 at r1](https://reviewable.io/reviews/saltastroops/remote-command-server/1#-MR_S7aCCes1eYo0W0ic:-MR_S7aCCes1eYo0W0id:bpo5f7h) ([raw file](https://github.com/saltastroops/remote-command-server/blob/9bc5b2d5fed4a7342834bf089a06494754d9a01c/tests/test_remote_command_server.py#L30)):*
> ```Python
>     """Invalid request bodies lead to a 422 error."""
>     response = client.post("/deploy", json=body)
>     print(response.text)
> ```

debug statement

**Review by Eb-Zeero — COMMENTED** [review]
> Reviewed 2 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/remote-command-server/1)* status: 17 of 19 files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Review by Eb-Zeero — COMMENTED** [review]
> Reviewed 1 of 19 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/remote-command-server/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Comment by hettlage** [comment]
Dealt with in PR #2.

**Pull request closed without merging**
